// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'base': string;
  'isActive': string;
  'shadow': string;
}
const cssExports: CssExports;
export default cssExports;
