// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'baseStack': string;
  'filtersBox': string;
  'searchArea': string;
  'searchBox': string;
}
const cssExports: CssExports;
export default cssExports;
